/**
 * Async Discipline Guard Plugin Generator — FR-K01/K02/K03
 *
 * Generates a Gateway-loadable ESM plugin file that blocks main-session
 * process(poll/wait/log/list) calls with long timeouts. FR-K02 uses Ark
 * embedding cosine similarity for one-call exemptions. FR-K03 uses degradedAt
 * timestamp recovery.
 */

import { writeFile, mkdir, access, readFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import type { Generator, GeneratorEnv } from './index.js';
import type { AcoFileConfig } from '../config/config-schema.js';
import { DEFAULT_ASYNC_DISCIPLINE_CONFIG } from '../control/async-discipline-guard.js';
import { SEMANTIC_VECTOR_DB_PATH, SEMANTIC_VECTOR_MODEL } from '../shared/semantic-vector-classifier.js';

export interface AsyncDisciplineGuardPluginOptions {
  enabled?: boolean;
  maxBlockingTimeoutMs?: number;
  blockingActions?: string[];
  vectorJudgement?: {
    enabled?: boolean;
    timeoutMs?: number;
  };
  degradedRecoveryWindowMs?: number;
  auditLogPath?: string;
  pluginName?: string;
  pluginVersion?: string;
}

const DEFAULT_OPTIONS: Required<AsyncDisciplineGuardPluginOptions> = {
  enabled: DEFAULT_ASYNC_DISCIPLINE_CONFIG.enabled,
  maxBlockingTimeoutMs: DEFAULT_ASYNC_DISCIPLINE_CONFIG.maxBlockingTimeoutMs,
  blockingActions: DEFAULT_ASYNC_DISCIPLINE_CONFIG.blockingActions,
  vectorJudgement: DEFAULT_ASYNC_DISCIPLINE_CONFIG.vectorJudgement,
  degradedRecoveryWindowMs: DEFAULT_ASYNC_DISCIPLINE_CONFIG.degradedRecoveryWindowMs,
  auditLogPath: '',
  pluginName: 'aco-async-discipline-guard',
  pluginVersion: '1.1.0',
};

function mergeOptions(options?: AsyncDisciplineGuardPluginOptions): Required<AsyncDisciplineGuardPluginOptions> {
  const rawVector = options?.vectorJudgement ?? {};
  return {
    enabled: options?.enabled ?? DEFAULT_OPTIONS.enabled,
    maxBlockingTimeoutMs: options?.maxBlockingTimeoutMs ?? DEFAULT_OPTIONS.maxBlockingTimeoutMs,
    blockingActions: options?.blockingActions ?? DEFAULT_OPTIONS.blockingActions,
    vectorJudgement: {
      enabled: rawVector.enabled ?? DEFAULT_OPTIONS.vectorJudgement.enabled,
      timeoutMs: rawVector.timeoutMs ?? DEFAULT_OPTIONS.vectorJudgement.timeoutMs,
    },
    degradedRecoveryWindowMs: options?.degradedRecoveryWindowMs ?? DEFAULT_OPTIONS.degradedRecoveryWindowMs,
    auditLogPath: options?.auditLogPath ?? DEFAULT_OPTIONS.auditLogPath,
    pluginName: options?.pluginName ?? DEFAULT_OPTIONS.pluginName,
    pluginVersion: options?.pluginVersion ?? DEFAULT_OPTIONS.pluginVersion,
  };
}

function loadEmbeddedVectorDb(): unknown {
  return JSON.parse(readFileSync(SEMANTIC_VECTOR_DB_PATH, 'utf-8'));
}

export function generateAsyncDisciplineGuardPlugin(options?: AsyncDisciplineGuardPluginOptions): string {
  const opts = mergeOptions(options);
  const auditLogLine = opts.auditLogPath
    ? `const AUDIT_LOG_PATH = ${JSON.stringify(opts.auditLogPath)};`
    : `const AUDIT_LOG_PATH = path.join(process.env.HOME || os.homedir(), '.openclaw', 'workspace', 'logs', 'dispatch-guard-events.jsonl');`;
  const embeddedVectorDb = loadEmbeddedVectorDb();

  return `/**
 * ACO Async Discipline Guard Plugin — Gateway-loadable ESM module
 * Generated by \`aco init\`
 *
 * Hooks: before_prompt_build, before_tool_call
 * Rule: dispatch.process.async_discipline_blocked
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';

${auditLogLine}

const VECTOR_INTENT_DOMAIN = 'async-exemption-intent';
const VECTOR_MODEL = ${JSON.stringify(SEMANTIC_VECTOR_MODEL)};
const VECTOR_DB = ${JSON.stringify(embeddedVectorDb)};

export const DEFAULT_CONFIG = ${JSON.stringify({
  enabled: opts.enabled,
  maxBlockingTimeoutMs: opts.maxBlockingTimeoutMs,
  blockingActions: opts.blockingActions,
  vectorJudgement: opts.vectorJudgement,
  degradedRecoveryWindowMs: opts.degradedRecoveryWindowMs,
}, null, 2)};

export default {
  name: ${JSON.stringify(opts.pluginName)},
  version: ${JSON.stringify(opts.pluginVersion)},

  register(api) {
    const recentUserMessageCache = new Map();
    const embeddingCache = new Map();
    let degradedAt = null;

    function getPluginConfig() {
      const pluginEntry = api.pluginConfig?.[${JSON.stringify(opts.pluginName)}];
      const dispatchEntry = api.pluginConfig?.['aco-dispatch-guard'] || api.pluginConfig?.['agent-dispatch-guard'];
      const pluginConfig = pluginEntry?.config || pluginEntry || dispatchEntry?.asyncDisciplineGuard || dispatchEntry || {};
      const raw = pluginConfig.asyncDisciplineGuard || pluginConfig;
      const legacyField = ['user', 'Exempt', 'Keywords'].join('');
      if (Object.prototype.hasOwnProperty.call(raw, legacyField)) {
        api.logger?.warn?.('[${opts.pluginName}] FR-K02: legacy keyword exemption config is deprecated and ignored; exemption now uses embedding cosine similarity.');
      }
      const cfg = { ...DEFAULT_CONFIG, ...raw, vectorJudgement: { ...DEFAULT_CONFIG.vectorJudgement, ...(raw.vectorJudgement || {}) } };
      delete cfg[legacyField];
      delete cfg[['llm', 'Judgement'].join('')];
      if (!Number.isFinite(Number(cfg.maxBlockingTimeoutMs)) || Number(cfg.maxBlockingTimeoutMs) <= 0) {
        api.logger?.warn?.('[${opts.pluginName}] invalid maxBlockingTimeoutMs, fallback to 5000');
        cfg.maxBlockingTimeoutMs = 5000;
      }
      if (!Array.isArray(cfg.blockingActions) || cfg.blockingActions.length === 0) cfg.blockingActions = DEFAULT_CONFIG.blockingActions;
      const recovery = Number(cfg.degradedRecoveryWindowMs ?? cfg.degradedRecoverIntervalMs);
      if (!Number.isFinite(recovery) || recovery < 60000 || recovery > 3600000) {
        api.logger?.warn?.('[${opts.pluginName}] asyncDisciplineGuard.degradedRecoveryWindowMs out of range, fallback to default 300000');
        cfg.degradedRecoveryWindowMs = 300000;
      } else {
        cfg.degradedRecoveryWindowMs = recovery;
      }
      if (!Number.isFinite(Number(cfg.vectorJudgement.timeoutMs)) || Number(cfg.vectorJudgement.timeoutMs) <= 0) cfg.vectorJudgement.timeoutMs = 8000;
      return cfg;
    }

    function extractSessionKey(event, context) {
      return String(context?.sessionKey || event?.sessionKey || event?.session?.sessionKey || '');
    }

    function extractAgentId(event, context, sessionKey) {
      const explicit = context?.agentId || event?.agentId || event?.session?.agentId;
      if (explicit) return String(explicit);
      const parts = String(sessionKey || '').split(':');
      if (parts[0] === 'agent' && parts[1]) return parts[1];
      return 'unknown';
    }

    function isMainSession(sessionKey, agentId) {
      return agentId === 'main' || String(sessionKey || '').includes(':main:') || String(sessionKey || '').startsWith('agent:main:');
    }

    function extractText(content) {
      if (typeof content === 'string') return content;
      if (Array.isArray(content)) {
        return content.map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object' && typeof item.text === 'string') return item.text;
          return '';
        }).filter(Boolean).join('\\n');
      }
      if (content && typeof content === 'object' && typeof content.text === 'string') return content.text;
      return '';
    }

    function captureRecentUserMessage(event, context) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      if (!isMainSession(sessionKey, agentId)) return;
      const messages = event?.messages || context?.messages || event?.prompt?.messages || [];
      if (!Array.isArray(messages)) return;
      for (let i = messages.length - 1; i >= 0; i--) {
        const msg = messages[i];
        if (!msg || msg.role !== 'user') continue;
        const text = extractText(msg.content ?? msg.text ?? msg.message);
        if (text) {
          recentUserMessageCache.set(sessionKey, { text, ts: Date.now() });
          if (recentUserMessageCache.size > 200) {
            const cutoff = Date.now() - 24 * 60 * 60 * 1000;
            for (const [key, value] of recentUserMessageCache) if (value.ts < cutoff) recentUserMessageCache.delete(key);
          }
        }
        return;
      }
    }

    function hashMessage(text) {
      if (text === null || text === undefined) return 'cache_miss';
      return crypto.createHash('sha256').update(String(text)).digest('hex').slice(0, 16);
    }

    function summarizeToolArgs(args) {
      const out = {};
      for (const [key, value] of Object.entries(args || {})) {
        if (typeof value === 'string') out[key] = value.length > 60 ? value.slice(0, 60) + '…' : value;
        else if (value === null || ['number', 'boolean'].includes(typeof value)) out[key] = value;
        else out[key] = JSON.stringify(value).slice(0, 60);
      }
      return out;
    }

    function appendAuditEvent(entry) {
      try {
        fs.mkdirSync(path.dirname(AUDIT_LOG_PATH), { recursive: true });
        fs.appendFileSync(AUDIT_LOG_PATH, JSON.stringify(entry) + '\\n');
      } catch (e) {
        api.logger?.warn?.('[${opts.pluginName}] audit log write failed: ' + e.message);
      }
    }

    function buildBlockReason(action, timeoutMs) {
      return [
        \`[ACO 异步纪律守卫] 主会话被禁止调用 process(action=\${action || 'unknown'}, timeout=\${timeoutMs}ms) 同步等待。\`,
        '原因: 此调用会锁住主会话 lane，期间用户 IM 消息会被静默排队，体感等同失联。',
        '',
        '合规路径(任选其一):',
        '  1. 信任 push-based completion event。spawn 后直接结束当前回合，子 Agent 完成时会自动触发新回合，无需主动 poll。',
        '  2. 确实需要观察某个进程状态，改派一个短任务子 Agent 异步执行 poll，完成后通过 completion event 回报结果。',
        '',
        '豁免方式: 用户在最近一条 IM 消息中明确表达让主会话本回合亲自执行这件事的意图，由向量匹配判定。',
        '豁免仅本次有效，下次调用重新走完整守卫。',
        '',
        '命中规则: dispatch.process.async_discipline_blocked',
      ].join('\\n');
    }

    function audit({ decision, ruleId, reason, event, context, vectorVerdict = 'not_applicable', vectorLatencyMs = 0, vectorError = null, vectorModel = null, vectorScore = null, vectorConfidenceBand = null, matchedSampleId = null, details = {} }) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;
      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const timestamp = new Date().toISOString();
      appendAuditEvent({
        ts: timestamp,
        timestamp,
        eventType: 'dispatch.process.async_discipline',
        rule: 'async-discipline',
        ruleId,
        decision,
        toolName: 'process',
        sessionKey,
        agentId,
        action,
        timeoutMs,
        toolArgs: summarizeToolArgs(params),
        exemptKeyword: null,
        triggerKeyword: null,
        recentUserMessageHash: hashMessage(recent),
        vectorVerdict,
        vectorLatencyMs,
        vectorError,
        vectorModel,
        vectorScore,
        vectorConfidenceBand,
        reason,
        details: { rule: 'async-discipline', ruleId, decision, action, timeoutMs, exemptKeyword: null, triggerKeyword: null, recentUserMessageHash: hashMessage(recent), vectorVerdict, vectorLatencyMs, vectorError, vectorModel, vectorScore, vectorConfidenceBand, matchedSampleId, reason, ...details },
      });
    }

    function readEmbeddingConfig() {
      const provider = api.config?.models?.providers?.['volcengine-ark'] || {};
      const apiKey = process.env.ARK_API_KEY || provider.apiKey;
      const baseUrl = String(provider.baseUrl || provider.baseURL || 'https://ark.cn-beijing.volces.com/api/v3').replace(/\\/+$/, '');
      if (!apiKey) return null;
      return { baseUrl, apiKey, model: VECTOR_MODEL, providerId: 'volcengine-ark' };
    }

    async function embedText(text, timeoutMs) {
      const normalized = String(text || '').replace(/\\s+/g, ' ').trim();
      if (!normalized) return null;
      const cfg = readEmbeddingConfig();
      if (!cfg) return null;
      const cacheKey = cfg.model + ':' + normalized;
      if (embeddingCache.has(cacheKey)) return embeddingCache.get(cacheKey);
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        const response = await fetch(cfg.baseUrl + '/embeddings/multimodal', {
          method: 'POST',
          signal: controller.signal,
          headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + cfg.apiKey },
          body: JSON.stringify({ model: cfg.model, input: [{ type: 'text', text: normalized.slice(0, 4000) }], encoding_format: 'float' }),
        });
        if (!response.ok) return null;
        const payload = await response.json();
        const vector = Array.isArray(payload?.data) ? payload.data[0]?.embedding : payload?.data?.embedding;
        if (!Array.isArray(vector) || vector.length !== VECTOR_DB.dimensions) return null;
        const numeric = vector.map(Number);
        if (numeric.some(v => !Number.isFinite(v))) return null;
        embeddingCache.set(cacheKey, numeric);
        return numeric;
      } catch {
        return null;
      } finally {
        clearTimeout(timer);
      }
    }

    function cosineSimilarity(a, b) {
      if (!Array.isArray(a) || !Array.isArray(b) || a.length === 0 || a.length !== b.length) return -1;
      let dot = 0;
      let normA = 0;
      let normB = 0;
      for (let i = 0; i < a.length; i += 1) {
        const av = Number(a[i]);
        const bv = Number(b[i]);
        if (!Number.isFinite(av) || !Number.isFinite(bv)) return -1;
        dot += av * bv;
        normA += av * av;
        normB += bv * bv;
      }
      if (normA === 0 || normB === 0) return -1;
      return dot / (Math.sqrt(normA) * Math.sqrt(normB));
    }

    async function vectorIntentJudgement(cfg, recent) {
      if (cfg.vectorJudgement?.enabled === false) return { vectorVerdict: 'disabled', vectorLatencyMs: 0, vectorError: null, vectorModel: null, vectorScore: null, vectorConfidenceBand: null };
      const started = Date.now();
      const timeoutLimit = Number(cfg.vectorJudgement.timeoutMs || 8000);
      try {
        const query = await embedText(recent || '', timeoutLimit);
        if (!query) return { vectorVerdict: 'unavailable', vectorLatencyMs: Math.max(0, Date.now() - started), vectorError: 'query embedding unavailable', vectorModel: VECTOR_MODEL, vectorScore: null, vectorConfidenceBand: null };
        const samples = VECTOR_DB.samples.filter(sample => sample.domain === VECTOR_INTENT_DOMAIN);
        let best = null;
        for (const sample of samples) {
          const score = cosineSimilarity(query, sample.vector);
          if (!best || score > best.score) best = { sample, score };
        }
        if (!best) return { vectorVerdict: 'unavailable', vectorLatencyMs: Math.max(0, Date.now() - started), vectorError: 'no comparable vectors', vectorModel: VECTOR_MODEL, vectorScore: null, vectorConfidenceBand: null };
        const band = best.score >= VECTOR_DB.thresholds.direct ? 'direct' : best.score >= VECTOR_DB.thresholds.fallback ? 'fallback' : 'none';
        if (band === 'none') return { vectorVerdict: 'unavailable', vectorLatencyMs: Math.max(0, Date.now() - started), vectorError: 'below vector threshold', vectorModel: VECTOR_MODEL, vectorScore: best.score, vectorConfidenceBand: band, matchedSampleId: best.sample.id };
        return { vectorVerdict: best.sample.label === 'deny' ? 'deny' : 'allow', vectorLatencyMs: Math.max(0, Date.now() - started), vectorError: null, vectorModel: VECTOR_MODEL, vectorScore: best.score, vectorConfidenceBand: band, matchedSampleId: best.sample.id };
      } catch (e) {
        return { vectorVerdict: 'unavailable', vectorLatencyMs: Math.max(0, Date.now() - started), vectorError: String(e?.message || e).slice(0, 256), vectorModel: VECTOR_MODEL, vectorScore: null, vectorConfidenceBand: null };
      }
    }

    async function evaluateAsyncDiscipline(event, context, cfg) {
      const toolName = String(event?.toolName || context?.toolName || '');
      if (toolName !== 'process') return null;
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;

      if (cfg.enabled === false) {
        audit({ decision: 'bypass_disabled', ruleId: 'dispatch.process.async_discipline_bypass_disabled', reason: 'Async discipline guard is disabled by configuration.', event, context });
        return null;
      }

      const now = Date.now();
      if (degradedAt !== null) {
        const elapsed = now - degradedAt;
        if (elapsed < cfg.degradedRecoveryWindowMs) {
          audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard is degraded; allowing tool call.', event, context, details: { degradedAt } });
          return null;
        }
        const previousDegradedAt = degradedAt;
        degradedAt = null;
        audit({ decision: 'recovery_attempt', ruleId: 'dispatch.process.async_discipline_recovery_attempt', reason: 'Async discipline guard recovery window elapsed; attempting normal evaluation.', event, context, details: { previousDegradedAt, recoveryWindowMs: cfg.degradedRecoveryWindowMs, elapsedMs: elapsed } });
      }

      if (!isMainSession(sessionKey, agentId)) return null;
      if (!cfg.blockingActions.map(a => String(a).toLowerCase()).includes(action.toLowerCase())) return null;
      if (timeoutMs < cfg.maxBlockingTimeoutMs) return null;

      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const vector = await vectorIntentJudgement(cfg, recent);
      if (vector.vectorVerdict !== 'deny') {
        audit({ decision: 'exempt', ruleId: 'dispatch.process.async_discipline_exempted', reason: vector.vectorVerdict === 'allow' ? 'User exemption intent matched by embedding cosine similarity.' : 'Embedding classifier unavailable; allowing tool call without LLM fallback.', event, context, ...vector });
        return null;
      }

      const reason = buildBlockReason(action, timeoutMs);
      audit({ decision: 'block', ruleId: 'dispatch.process.async_discipline_blocked', reason, event, context, ...vector });
      return { block: true, blockReason: reason };
    }

    api.on('before_prompt_build', (event, context) => {
      try { captureRecentUserMessage(event, context); }
      catch (e) { api.logger?.warn?.('[${opts.pluginName}] recent user cache error: ' + e.message); }
      return null;
    }, { priority: 970 });

    api.on('before_tool_call', async function(event, context) {
      try {
        const cfg = getPluginConfig();
        return await evaluateAsyncDiscipline(event, context, cfg);
      } catch (e) {
        degradedAt = Date.now();
        api.logger?.warn?.('[${opts.pluginName}] degraded: ' + e.message);
        try { audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard runtime error: ' + String(e.message || e).slice(0, 256), event, context, details: { degradedAt, error: String(e.message || e).slice(0, 256), stackTop: String(e.stack || '').split('\\n').slice(0, 3).join('\\n').slice(0, 512) } }); } catch {}
        return null;
      }
    });
  },
};
`;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function providerHasApiKey(openclawConfig: Record<string, unknown>): boolean {
  const providers = (openclawConfig.models as Record<string, unknown> | undefined)?.providers as Record<string, unknown> | undefined;
  const entry = providers?.['volcengine-ark'] as Record<string, unknown> | undefined;
  return Boolean(process.env.ARK_API_KEY || entry?.apiKey);
}

async function assertVectorProviderConfigured(env: GeneratorEnv, guardConfig: AcoFileConfig['asyncDisciplineGuard']): Promise<void> {
  const vector = guardConfig?.vectorJudgement ?? DEFAULT_ASYNC_DISCIPLINE_CONFIG.vectorJudgement;
  if (vector.enabled === false) return;
  if (!env.openclawConfigPath) {
    throw new Error(`aco init failed: OpenClaw config was not detected.
Next steps:
  1. If you use OpenClaw, set OPENCLAW_HOME to the directory that contains openclaw.json, then rerun aco init.
  2. If you only want to see ACO behavior, run aco demo. It does not require OpenClaw, providers, or network access.
  3. If you want init without the async discipline vector guard, create aco.config.json with:
     { "asyncDisciplineGuard": { "vectorJudgement": { "enabled": false } } }`);
  }
  const raw = await readFile(env.openclawConfigPath, 'utf-8');
  const openclawConfig = JSON.parse(raw) as Record<string, unknown>;
  if (!providerHasApiKey(openclawConfig)) {
    throw new Error(`aco init failed: asyncDisciplineGuard.vectorJudgement requires volcengine-ark API key for ${SEMANTIC_VECTOR_MODEL}.
Next steps:
  1. Set ARK_API_KEY, or configure models.providers.volcengine-ark.apiKey in ${env.openclawConfigPath}.
  2. Or disable this guard for first setup:
     { "asyncDisciplineGuard": { "vectorJudgement": { "enabled": false } } }
  3. To see ACO without provider setup, run aco demo.`);
  }
}

const asyncDisciplineGuardGenerator: Generator = {
  name: 'async-discipline-guard-plugin',
  description: 'Generates the FR-K01/K02/K03 async discipline guard Gateway plugin',
  priority: 60,
  async validate(env: GeneratorEnv, config: AcoFileConfig | null): Promise<void> {
    const guardConfig = config?.asyncDisciplineGuard ?? {};
    if (guardConfig.enabled === false) return;
    await assertVectorProviderConfigured(env, guardConfig);
  },
  async generate(env: GeneratorEnv, config: AcoFileConfig | null, force: boolean): Promise<void> {
    const guardConfig = config?.asyncDisciplineGuard ?? {};
    if (guardConfig.enabled === false) return;
    await assertVectorProviderConfigured(env, guardConfig);

    const outputPath = join(env.openclawHome, 'extensions', 'aco-async-discipline-guard', 'index.js');
    if ((await exists(outputPath)) && !force) {
      console.log(`  - Async discipline guard plugin already exists: ${outputPath}`);
      console.log('    Skipped. Use --force to overwrite.');
      return;
    }

    await mkdir(dirname(outputPath), { recursive: true });
    const plugin = generateAsyncDisciplineGuardPlugin({
      enabled: guardConfig.enabled,
      maxBlockingTimeoutMs: guardConfig.maxBlockingTimeoutMs,
      blockingActions: guardConfig.blockingActions,
      vectorJudgement: guardConfig.vectorJudgement,
      degradedRecoveryWindowMs: guardConfig.degradedRecoveryWindowMs ?? guardConfig.degradedRecoverIntervalMs,
      auditLogPath: join(env.openclawHome, 'workspace', 'logs', 'dispatch-guard-events.jsonl'),
    });
    await writeFile(outputPath, plugin, 'utf-8');
    console.log(`  ✓ Async discipline guard plugin written: ${outputPath}`);
  },
};

export default asyncDisciplineGuardGenerator;
