/**
 * Async Discipline Guard Plugin Generator — FR-K01/K02/K03
 *
 * Generates a Gateway-loadable ESM plugin file that blocks main-session
 * process(poll/wait/log/list) calls with long timeouts. FR-K02 uses LLM
 * semantic intent judgement for one-call exemptions. FR-K03 uses degradedAt
 * timestamp recovery.
 */

import { writeFile, mkdir, access, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { Generator, GeneratorEnv } from './index.js';
import type { AcoFileConfig } from '../config/config-schema.js';
import { DEFAULT_ASYNC_DISCIPLINE_CONFIG, LLM_INTENT_JUDGEMENT_PROMPT_V1 } from '../control/async-discipline-guard.js';

export interface AsyncDisciplineGuardPluginOptions {
  enabled?: boolean;
  maxBlockingTimeoutMs?: number;
  blockingActions?: string[];
  llmJudgement?: {
    enabled?: boolean;
    provider?: string;
    model?: string;
    timeoutMs?: number;
  };
  degradedRecoveryWindowMs?: number;
  auditLogPath?: string;
  pluginName?: string;
  pluginVersion?: string;
}

const DEFAULT_OPTIONS: Required<AsyncDisciplineGuardPluginOptions> = {
  enabled: DEFAULT_ASYNC_DISCIPLINE_CONFIG.enabled,
  maxBlockingTimeoutMs: DEFAULT_ASYNC_DISCIPLINE_CONFIG.maxBlockingTimeoutMs,
  blockingActions: DEFAULT_ASYNC_DISCIPLINE_CONFIG.blockingActions,
  llmJudgement: DEFAULT_ASYNC_DISCIPLINE_CONFIG.llmJudgement,
  degradedRecoveryWindowMs: DEFAULT_ASYNC_DISCIPLINE_CONFIG.degradedRecoveryWindowMs,
  auditLogPath: '',
  pluginName: 'aco-async-discipline-guard',
  pluginVersion: '1.1.0',
};

function mergeOptions(options?: AsyncDisciplineGuardPluginOptions): Required<AsyncDisciplineGuardPluginOptions> {
  const rawLlm = options?.llmJudgement ?? {};
  return {
    enabled: options?.enabled ?? DEFAULT_OPTIONS.enabled,
    maxBlockingTimeoutMs: options?.maxBlockingTimeoutMs ?? DEFAULT_OPTIONS.maxBlockingTimeoutMs,
    blockingActions: options?.blockingActions ?? DEFAULT_OPTIONS.blockingActions,
    llmJudgement: {
      enabled: rawLlm.enabled ?? DEFAULT_OPTIONS.llmJudgement.enabled,
      provider: rawLlm.provider ?? DEFAULT_OPTIONS.llmJudgement.provider,
      model: rawLlm.model ?? DEFAULT_OPTIONS.llmJudgement.model,
      timeoutMs: rawLlm.timeoutMs ?? DEFAULT_OPTIONS.llmJudgement.timeoutMs,
    },
    degradedRecoveryWindowMs: options?.degradedRecoveryWindowMs ?? DEFAULT_OPTIONS.degradedRecoveryWindowMs,
    auditLogPath: options?.auditLogPath ?? DEFAULT_OPTIONS.auditLogPath,
    pluginName: options?.pluginName ?? DEFAULT_OPTIONS.pluginName,
    pluginVersion: options?.pluginVersion ?? DEFAULT_OPTIONS.pluginVersion,
  };
}

export function generateAsyncDisciplineGuardPlugin(options?: AsyncDisciplineGuardPluginOptions): string {
  const opts = mergeOptions(options);
  const auditLogLine = opts.auditLogPath
    ? `const AUDIT_LOG_PATH = ${JSON.stringify(opts.auditLogPath)};`
    : `const AUDIT_LOG_PATH = path.join(process.env.HOME || os.homedir(), '.openclaw', 'workspace', 'logs', 'dispatch-guard-events.jsonl');`;

  return `/**
 * ACO Async Discipline Guard Plugin — Gateway-loadable ESM module
 * Generated by \`aco init\`
 *
 * Hooks: before_prompt_build, before_tool_call
 * Rule: dispatch.process.async_discipline_blocked
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';

${auditLogLine}

const LLM_INTENT_JUDGEMENT_PROMPT_VERSION = 'v1';
const LLM_INTENT_JUDGEMENT_PROMPT_V1 = ${JSON.stringify(LLM_INTENT_JUDGEMENT_PROMPT_V1)};

export const DEFAULT_CONFIG = ${JSON.stringify({
  enabled: opts.enabled,
  maxBlockingTimeoutMs: opts.maxBlockingTimeoutMs,
  blockingActions: opts.blockingActions,
  llmJudgement: opts.llmJudgement,
  degradedRecoveryWindowMs: opts.degradedRecoveryWindowMs,
}, null, 2)};

export default {
  name: ${JSON.stringify(opts.pluginName)},
  version: ${JSON.stringify(opts.pluginVersion)},

  register(api) {
    const recentUserMessageCache = new Map();
    let degradedAt = null;

    function getPluginConfig() {
      const pluginEntry = api.pluginConfig?.[${JSON.stringify(opts.pluginName)}];
      const dispatchEntry = api.pluginConfig?.['aco-dispatch-guard'] || api.pluginConfig?.['agent-dispatch-guard'];
      const pluginConfig = pluginEntry?.config || pluginEntry || dispatchEntry?.asyncDisciplineGuard || dispatchEntry || {};
      const raw = pluginConfig.asyncDisciplineGuard || pluginConfig;
      const legacyField = ['user', 'Exempt', 'Keywords'].join('');
      if (Object.prototype.hasOwnProperty.call(raw, legacyField)) {
        api.logger?.warn?.('[${opts.pluginName}] FR-K02: legacy keyword exemption config is deprecated and ignored; exemption now uses LLM semantic intent judgement.');
      }
      const cfg = { ...DEFAULT_CONFIG, ...raw, llmJudgement: { ...DEFAULT_CONFIG.llmJudgement, ...(raw.llmJudgement || {}) } };
      delete cfg[legacyField];
      if (!Number.isFinite(Number(cfg.maxBlockingTimeoutMs)) || Number(cfg.maxBlockingTimeoutMs) <= 0) {
        api.logger?.warn?.('[${opts.pluginName}] invalid maxBlockingTimeoutMs, fallback to 5000');
        cfg.maxBlockingTimeoutMs = 5000;
      }
      if (!Array.isArray(cfg.blockingActions) || cfg.blockingActions.length === 0) cfg.blockingActions = DEFAULT_CONFIG.blockingActions;
      const recovery = Number(cfg.degradedRecoveryWindowMs ?? cfg.degradedRecoverIntervalMs);
      if (!Number.isFinite(recovery) || recovery < 60000 || recovery > 3600000) {
        api.logger?.warn?.('[${opts.pluginName}] asyncDisciplineGuard.degradedRecoveryWindowMs out of range, fallback to default 300000');
        cfg.degradedRecoveryWindowMs = 300000;
      } else {
        cfg.degradedRecoveryWindowMs = recovery;
      }
      if (!Number.isFinite(Number(cfg.llmJudgement.timeoutMs)) || Number(cfg.llmJudgement.timeoutMs) <= 0) cfg.llmJudgement.timeoutMs = 5000;
      if (!isConfiguredModel(api.config, cfg.llmJudgement.provider, cfg.llmJudgement.model)) {
        api.logger?.error?.('[${opts.pluginName}] asyncDisciplineGuard.llmJudgement provider/model is not configured in models.providers; judgement will block exemptions.');
      }
      return cfg;
    }

    function isConfiguredModel(config, provider, model) {
      const models = config?.models?.providers?.[provider]?.models;
      if (Array.isArray(models)) return models.some(m => (typeof m === 'string' ? m : m?.id) === model);
      return Boolean(models && typeof models === 'object' && Object.prototype.hasOwnProperty.call(models, model));
    }

    function extractSessionKey(event, context) {
      return String(context?.sessionKey || event?.sessionKey || event?.session?.sessionKey || '');
    }

    function extractAgentId(event, context, sessionKey) {
      const explicit = context?.agentId || event?.agentId || event?.session?.agentId;
      if (explicit) return String(explicit);
      const parts = String(sessionKey || '').split(':');
      if (parts[0] === 'agent' && parts[1]) return parts[1];
      return 'unknown';
    }

    function isMainSession(sessionKey, agentId) {
      return agentId === 'main' || String(sessionKey || '').includes(':main:') || String(sessionKey || '').startsWith('agent:main:');
    }

    function extractText(content) {
      if (typeof content === 'string') return content;
      if (Array.isArray(content)) {
        return content.map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object' && typeof item.text === 'string') return item.text;
          return '';
        }).filter(Boolean).join('\\n');
      }
      if (content && typeof content === 'object' && typeof content.text === 'string') return content.text;
      return '';
    }

    function captureRecentUserMessage(event, context) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      if (!isMainSession(sessionKey, agentId)) return;
      const messages = event?.messages || context?.messages || event?.prompt?.messages || [];
      if (!Array.isArray(messages)) return;
      for (let i = messages.length - 1; i >= 0; i--) {
        const msg = messages[i];
        if (!msg || msg.role !== 'user') continue;
        const text = extractText(msg.content ?? msg.text ?? msg.message);
        if (text) {
          recentUserMessageCache.set(sessionKey, { text, ts: Date.now() });
          if (recentUserMessageCache.size > 200) {
            const cutoff = Date.now() - 24 * 60 * 60 * 1000;
            for (const [key, value] of recentUserMessageCache) if (value.ts < cutoff) recentUserMessageCache.delete(key);
          }
        }
        return;
      }
    }

    function hashMessage(text) {
      if (text === null || text === undefined) return 'cache_miss';
      return crypto.createHash('sha256').update(String(text)).digest('hex').slice(0, 16);
    }

    function summarizeToolArgs(args) {
      const out = {};
      for (const [key, value] of Object.entries(args || {})) {
        if (typeof value === 'string') out[key] = value.length > 60 ? value.slice(0, 60) + '…' : value;
        else if (value === null || ['number', 'boolean'].includes(typeof value)) out[key] = value;
        else out[key] = JSON.stringify(value).slice(0, 60);
      }
      return out;
    }

    function appendAuditEvent(entry) {
      try {
        fs.mkdirSync(path.dirname(AUDIT_LOG_PATH), { recursive: true });
        fs.appendFileSync(AUDIT_LOG_PATH, JSON.stringify(entry) + '\\n');
      } catch (e) {
        api.logger?.warn?.('[${opts.pluginName}] audit log write failed: ' + e.message);
      }
    }

    function buildBlockReason(action, timeoutMs) {
      return [
        \`[ACO 异步纪律守卫] 主会话被禁止调用 process(action=\${action || 'unknown'}, timeout=\${timeoutMs}ms) 同步等待。\`,
        '原因: 此调用会锁住主会话 lane，期间用户 IM 消息会被静默排队，体感等同失联。',
        '',
        '合规路径(任选其一):',
        '  1. 信任 push-based completion event。spawn 后直接结束当前回合，子 Agent 完成时会自动触发新回合，无需主动 poll。',
        '  2. 确实需要观察某个进程状态，改派一个短任务子 Agent 异步执行 poll，完成后通过 completion event 回报结果。',
        '',
        '豁免方式: 用户在最近一条 IM 消息中明确表达让主会话本回合亲自执行这件事的意图，由 LLM 语义判定。',
        '豁免仅本次有效，下次调用重新走完整守卫。',
        '',
        '命中规则: dispatch.process.async_discipline_blocked',
      ].join('\\n');
    }

    function audit({ decision, ruleId, reason, event, context, llmVerdict = 'not_applicable', llmLatencyMs = 0, llmError = null, llmPromptVersion = null, details = {} }) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;
      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const timestamp = new Date().toISOString();
      appendAuditEvent({
        ts: timestamp,
        timestamp,
        eventType: 'dispatch.process.async_discipline',
        rule: 'async-discipline',
        ruleId,
        decision,
        toolName: 'process',
        sessionKey,
        agentId,
        action,
        timeoutMs,
        toolArgs: summarizeToolArgs(params),
        exemptKeyword: null,
        triggerKeyword: null,
        recentUserMessageHash: hashMessage(recent),
        llmVerdict,
        llmLatencyMs,
        llmError,
        llmPromptVersion,
        reason,
        details: { rule: 'async-discipline', ruleId, decision, action, timeoutMs, exemptKeyword: null, triggerKeyword: null, recentUserMessageHash: hashMessage(recent), llmVerdict, llmLatencyMs, llmError, llmPromptVersion, reason, ...details },
      });
    }

    function normalizeLlmIntentRaw(raw) {
      return String(raw ?? '').trim().toUpperCase().replace(/[\\p{P}\\p{S}]/gu, '');
    }

    function buildIntentMessages(recent) {
      return {
        system: LLM_INTENT_JUDGEMENT_PROMPT_V1,
        user: '请判断下面这条用户当前消息是否表达授权主会话本回合亲自执行长任务。\\n\\n\\x60\\x60\\x60\\n' + String(recent ?? '') + '\\n\\x60\\x60\\x60',
      };
    }

    async function callConfiguredChatProvider(cfg, messages, signal) {
      if (api.openclaw?.chat?.complete) {
        const res = await api.openclaw.chat.complete({ provider: cfg.llmJudgement.provider, model: cfg.llmJudgement.model, messages, signal });
        return res?.text ?? res?.content ?? res?.message?.content ?? '';
      }
      const providerCfg = api.config?.models?.providers?.[cfg.llmJudgement.provider];
      if (!providerCfg) throw new Error('provider not configured');
      const baseUrl = String(providerCfg.baseUrl || providerCfg.baseURL || '').replace(/\\/$/, '');
      const apiKey = providerCfg.apiKey || providerCfg.auth?.apiKey || providerCfg.request?.auth?.token;
      if (!baseUrl || !apiKey) throw new Error('provider baseUrl/apiKey unavailable');
      const response = await fetch(baseUrl + '/chat/completions', {
        method: 'POST',
        signal,
        headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + apiKey, ...(providerCfg.headers || {}) },
        body: JSON.stringify({ model: cfg.llmJudgement.model, messages, temperature: 0, max_tokens: 4 }),
      });
      if (!response.ok) throw new Error('provider HTTP ' + response.status);
      const data = await response.json();
      return data?.choices?.[0]?.message?.content ?? data?.choices?.[0]?.text ?? '';
    }

    async function llmIntentJudgement(cfg, recent, action, timeoutMs) {
      if (cfg.llmJudgement?.enabled === false) return { llmVerdict: 'disabled', llmLatencyMs: 0, llmError: null, llmPromptVersion: null };
      const started = Date.now();
      const controller = new AbortController();
      const timeoutLimit = Number(cfg.llmJudgement.timeoutMs || 5000);
      const timer = setTimeout(() => controller.abort(), timeoutLimit);
      try {
        const prompt = buildIntentMessages(recent);
        const raw = await callConfiguredChatProvider(cfg, [{ role: 'system', content: prompt.system }, { role: 'user', content: prompt.user }], controller.signal);
        const normalized = normalizeLlmIntentRaw(raw);
        return { llmVerdict: normalized === 'YES' ? 'allow' : 'deny', llmLatencyMs: Math.max(0, Date.now() - started), llmError: null, llmPromptVersion: LLM_INTENT_JUDGEMENT_PROMPT_VERSION };
      } catch (e) {
        const timeout = e?.name === 'AbortError';
        return { llmVerdict: timeout ? 'timeout' : 'error', llmLatencyMs: timeout ? timeoutLimit : Math.max(0, Date.now() - started), llmError: (timeout ? 'timeout' : String(e?.message || e)).slice(0, 256), llmPromptVersion: LLM_INTENT_JUDGEMENT_PROMPT_VERSION };
      } finally {
        clearTimeout(timer);
      }
    }

    async function evaluateAsyncDiscipline(event, context, cfg) {
      const toolName = String(event?.toolName || context?.toolName || '');
      if (toolName !== 'process') return null;
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;

      if (cfg.enabled === false) {
        audit({ decision: 'bypass_disabled', ruleId: 'dispatch.process.async_discipline_bypass_disabled', reason: 'Async discipline guard is disabled by configuration.', event, context });
        return null;
      }

      const now = Date.now();
      if (degradedAt !== null) {
        const elapsed = now - degradedAt;
        if (elapsed < cfg.degradedRecoveryWindowMs) {
          audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard is degraded; allowing tool call.', event, context, details: { degradedAt } });
          return null;
        }
        const previousDegradedAt = degradedAt;
        degradedAt = null;
        audit({ decision: 'recovery_attempt', ruleId: 'dispatch.process.async_discipline_recovery_attempt', reason: 'Async discipline guard recovery window elapsed; attempting normal evaluation.', event, context, details: { previousDegradedAt, recoveryWindowMs: cfg.degradedRecoveryWindowMs, elapsedMs: elapsed } });
      }

      if (!isMainSession(sessionKey, agentId)) return null;
      if (!cfg.blockingActions.map(a => String(a).toLowerCase()).includes(action.toLowerCase())) return null;
      if (timeoutMs < cfg.maxBlockingTimeoutMs) return null;

      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const llm = await llmIntentJudgement(cfg, recent, action, timeoutMs);
      if (llm.llmVerdict === 'allow') {
        audit({ decision: 'exempt', ruleId: 'dispatch.process.async_discipline_exempted', reason: 'User exemption intent judged by LLM.', event, context, ...llm });
        return null;
      }

      const reason = buildBlockReason(action, timeoutMs);
      audit({ decision: 'block', ruleId: 'dispatch.process.async_discipline_blocked', reason, event, context, ...llm });
      return { block: true, blockReason: reason };
    }

    api.on('before_prompt_build', (event, context) => {
      try { captureRecentUserMessage(event, context); }
      catch (e) { api.logger?.warn?.('[${opts.pluginName}] recent user cache error: ' + e.message); }
      return null;
    }, { priority: 970 });

    api.on('before_tool_call', async function(event, context) {
      try {
        const cfg = getPluginConfig();
        return await evaluateAsyncDiscipline(event, context, cfg);
      } catch (e) {
        degradedAt = Date.now();
        api.logger?.warn?.('[${opts.pluginName}] degraded: ' + e.message);
        try { audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard runtime error: ' + String(e.message || e).slice(0, 256), event, context, details: { degradedAt, error: String(e.message || e).slice(0, 256), stackTop: String(e.stack || '').split('\\n').slice(0, 3).join('\\n').slice(0, 512) } }); } catch {}
        return null;
      }
    });
  },
};
`;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function providerHasModel(openclawConfig: Record<string, unknown>, provider: string, model: string): boolean {
  const providers = (openclawConfig.models as Record<string, unknown> | undefined)?.providers as Record<string, unknown> | undefined;
  const entry = providers?.[provider] as Record<string, unknown> | undefined;
  const models = entry?.models;
  if (Array.isArray(models)) {
    return models.some(item => (typeof item === 'string' ? item : (item as Record<string, unknown>)?.id) === model);
  }
  return Boolean(models && typeof models === 'object' && Object.prototype.hasOwnProperty.call(models, model));
}

async function assertLlmModelConfigured(env: GeneratorEnv, guardConfig: AcoFileConfig['asyncDisciplineGuard']): Promise<void> {
  const llm = guardConfig?.llmJudgement ?? DEFAULT_ASYNC_DISCIPLINE_CONFIG.llmJudgement;
  const provider = llm.provider ?? DEFAULT_ASYNC_DISCIPLINE_CONFIG.llmJudgement.provider;
  const model = llm.model ?? DEFAULT_ASYNC_DISCIPLINE_CONFIG.llmJudgement.model;
  if (!env.openclawConfigPath) {
    throw new Error(`aco init failed: OpenClaw config was not detected.
Next steps:
  1. If you use OpenClaw, set OPENCLAW_HOME to the directory that contains openclaw.json, then rerun aco init.
  2. If you only want to see ACO behavior, run aco demo. It does not require OpenClaw, providers, or network access.
  3. If you want init without the async discipline LLM guard, create aco.config.json with:
     { "asyncDisciplineGuard": { "enabled": false } }`);
  }
  const raw = await readFile(env.openclawConfigPath, 'utf-8');
  const openclawConfig = JSON.parse(raw) as Record<string, unknown>;
  if (!providerHasModel(openclawConfig, provider, model)) {
    throw new Error(`aco init failed: asyncDisciplineGuard.llmJudgement model ${provider}/${model} is not present in ${env.openclawConfigPath}.
Next steps:
  1. Add the provider/model to openclaw.json under models.providers.${provider}.models, then rerun aco init.
     Example:
     {
       "models": {
         "providers": {
           "${provider}": {
             "models": ["${model}"]
           }
         }
       }
     }
  2. Or choose an existing model in aco.config.json:
     { "asyncDisciplineGuard": { "llmJudgement": { "provider": "<provider>", "model": "<model>" } } }
  3. Or disable this guard for first setup:
     { "asyncDisciplineGuard": { "enabled": false } }
  4. To see ACO without provider setup, run aco demo.`);
  }
}

const asyncDisciplineGuardGenerator: Generator = {
  name: 'async-discipline-guard-plugin',
  description: 'Generates the FR-K01/K02/K03 async discipline guard Gateway plugin',
  priority: 60,
  async validate(env: GeneratorEnv, config: AcoFileConfig | null): Promise<void> {
    const guardConfig = config?.asyncDisciplineGuard ?? {};
    if (guardConfig.enabled === false) return;
    await assertLlmModelConfigured(env, guardConfig);
  },
  async generate(env: GeneratorEnv, config: AcoFileConfig | null, force: boolean): Promise<void> {
    const guardConfig = config?.asyncDisciplineGuard ?? {};
    if (guardConfig.enabled === false) return;
    await assertLlmModelConfigured(env, guardConfig);

    const outputPath = join(env.openclawHome, 'extensions', 'aco-async-discipline-guard', 'index.js');
    if ((await exists(outputPath)) && !force) {
      console.log(`  - Async discipline guard plugin already exists: ${outputPath}`);
      console.log('    Skipped. Use --force to overwrite.');
      return;
    }

    await mkdir(dirname(outputPath), { recursive: true });
    const plugin = generateAsyncDisciplineGuardPlugin({
      enabled: guardConfig.enabled,
      maxBlockingTimeoutMs: guardConfig.maxBlockingTimeoutMs,
      blockingActions: guardConfig.blockingActions,
      llmJudgement: guardConfig.llmJudgement,
      degradedRecoveryWindowMs: guardConfig.degradedRecoveryWindowMs ?? guardConfig.degradedRecoverIntervalMs,
      auditLogPath: join(env.openclawHome, 'workspace', 'logs', 'dispatch-guard-events.jsonl'),
    });
    await writeFile(outputPath, plugin, 'utf-8');
    console.log(`  ✓ Async discipline guard plugin written: ${outputPath}`);
  },
};

export default asyncDisciplineGuardGenerator;
