/**
 * ACO Closure Guard Plugin — Gateway-loadable ESM module
 * Generated by `aco init`
 *
 * Hooks: subagent_ended, before_prompt_build, message_sending
 * Features: closure timeout detection, prompt injection reminder,
 *           post-reminder auto-close, next-turn detection, audit logging
 */

import fs from 'node:fs';
import path from 'node:path';

const AUDIT_LOG_PATH = "/root/.openclaw/workspace/logs/aco-closure-guard-events.jsonl";

export default {
  id: 'aco-closure-guard',
  name: "aco-closure-guard",
  version: "1.0.0",

  register(api) {
    const config = api.pluginConfig?.["aco-closure-guard"] || {};
    const excludeLabels = config.excludeLabels || undefined;
    const closureTimeoutMs = config.closureTimeoutMs || undefined;
    const autoCloseDelayMs = config.autoCloseDelayMs || 15000;

    // In-memory registry: track spawned subagents to correlate label + timing at end
    const spawnedSessions = new Map(); // childSessionKey -> { label, agentId, spawnedAt }

    // Pending closures: completions waiting for main session to send a summary
    // key: closureId, value: { agentId, label, duration, timer, completedAt, reminded }
    const pendingClosures = new Map();

    function shouldExclude(label) {
      if (!label) return false;
      return excludeLabels.some(pattern => {
        if (pattern.startsWith('/') && pattern.endsWith('/')) {
          try { return new RegExp(pattern.slice(1, -1)).test(label); } catch { return false; }
        }
        return label.startsWith(pattern);
      });
    }

    function formatDuration(ms) {
      if (!ms || ms <= 0) return '?';
      const sec = Math.round(ms / 1000);
      if (sec < 60) return `${sec}s`;
      const min = Math.floor(sec / 60);
      const remainSec = sec % 60;
      if (remainSec === 0) return `${min}min`;
      return `${min}m${remainSec}s`;
    }

    function extractAgentId(sessionKey) {
      if (!sessionKey) return 'unknown';
      const parts = sessionKey.split(':');
      if (parts.length >= 2 && parts[0] === 'agent') return parts[1];
      return 'unknown';
    }

    function appendAuditLog(entry) {
      try {
        fs.mkdirSync(path.dirname(AUDIT_LOG_PATH), { recursive: true });
        const record = {
          timestamp: new Date().toISOString(),
          plugin: "aco-closure-guard",
          ...entry,
        };
        fs.appendFileSync(AUDIT_LOG_PATH, JSON.stringify(record) + '\n');
      } catch (e) {
        api.logger?.warn?.(`[aco-closure-guard] audit log write failed: ${e.message}`);
      }
    }

    function handleClosureTimeout(closureId, data) {
      const { agentId, label, duration } = data;
      appendAuditLog({
        event: 'closure_missed',
        closureId,
        agentId,
        label,
        duration,
        reason: `no summary detected within ${closureTimeoutMs}ms`,
      });
      pendingClosures.delete(closureId);
    }

    // --- Hook: subagent_spawned ---
    api.on('subagent_spawned', (event) => {
      try {
        const key = event.childSessionKey;
        if (!key) return;
        spawnedSessions.set(key, {
          label: event.label || '',
          agentId: event.agentId || extractAgentId(key),
          spawnedAt: Date.now(),
        });
        // Prevent unbounded growth: prune entries older than 2 hours
        if (spawnedSessions.size > 200) {
          const cutoff = Date.now() - 2 * 60 * 60 * 1000;
          for (const [k, v] of spawnedSessions) {
            if (v.spawnedAt < cutoff) spawnedSessions.delete(k);
          }
        }
      } catch {}
    });

    // --- Hook: subagent_ended ---
    api.on('subagent_ended', (event) => {
      try {
        const sessionKey = event.targetSessionKey || '';
        const isAcp = sessionKey.includes(':acp:');
        const isSubagent = sessionKey.includes(':subagent:');
        if (!isAcp && !isSubagent) return;

        const spawnData = spawnedSessions.get(sessionKey);
        if (spawnData) spawnedSessions.delete(sessionKey);

        const agentId = spawnData?.agentId || extractAgentId(sessionKey);
        const label = spawnData?.label || '';
        if (shouldExclude(label)) return;

        const outcome = String(event.outcome || '').toLowerCase();
        const failed = outcome === 'error' || outcome === 'timeout';
        const icon = failed ? '❌' : '✅';

        let runtimeMs = 0;
        if (spawnData?.spawnedAt && event.endedAt) {
          runtimeMs = event.endedAt - spawnData.spawnedAt;
        } else if (spawnData?.spawnedAt) {
          runtimeMs = Date.now() - spawnData.spawnedAt;
        }
        const duration = formatDuration(runtimeMs);

        const closureId = `${agentId}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;

        const timer = setTimeout(() => {
          handleClosureTimeout(closureId, { agentId, label, duration, icon });
        }, closureTimeoutMs);
        if (timer.unref) timer.unref();

        pendingClosures.set(closureId, {
          agentId,
          label,
          duration,
          icon,
          timer,
          completedAt: Date.now(),
          sessionKey,
          reminded: false,
        });

        appendAuditLog({
          event: 'completion_registered',
          closureId,
          agentId,
          label,
          duration,
          outcome,
          timeoutMs: closureTimeoutMs,
        });
      } catch (e) {
        api.logger?.warn?.(`[aco-closure-guard] subagent_ended error: ${e.message}`);
      }
    });

    // --- Hook: before_prompt_build ---
    api.on(
      'before_prompt_build',
      (event, context) => {
        try {
          const ctx = context || event?.context || {};
          const sessionKey = String(ctx.sessionKey || event?.sessionKey || '');
          if (!sessionKey.includes('feishu')) return null;

          const agentId = String(ctx.agentId || '').trim();
          const effectiveAgentId = (!agentId || agentId === 'main') ? 'main' : agentId;
          if (effectiveAgentId !== 'main') return null;

          // AC15: Phase 1 — Clear previously-reminded closures (next-turn detection).
          // If we're in a new prompt build and closures were already reminded,
          // the main session already responded in the previous turn = closure.
          for (const [closureId, data] of pendingClosures) {
            if (data.reminded) {
              clearTimeout(data.timer);
              appendAuditLog({
                event: 'closure_detected',
                closureId,
                agentId: data.agentId,
                label: data.label,
                duration: data.duration,
                method: 'next_turn_detection',
                latencyMs: Date.now() - data.completedAt,
              });
              pendingClosures.delete(closureId);
            }
          }

          // Phase 2: Collect un-reminded pending completions
          const toRemind = [];
          for (const [closureId, data] of pendingClosures) {
            if (!data.reminded) {
              toRemind.push({ closureId, ...data });
            }
          }

          if (toRemind.length === 0) return null;

          // Build reminder text
          const lines = [
            '',
            '## ⚠️ [ACO Closure Guard] 飞书总结提醒（不可忽略）',
            '',
            '以下任务已完成，你**必须**用 \`lark-cli im +messages-send --user-id <userId> --markdown "..."\` 给用户发一条人话总结。不发 = 违规。',
            '',
          ];

          for (const item of toRemind) {
            lines.push(`- ${item.icon} **${item.label || '(无label)'}** | agent=${item.agentId} | 耗时=${item.duration}`);
          }

          lines.push('');
          lines.push('要求：总结用人话，包含结论+关键产出+状态。禁止技术标签。发完飞书后继续正常处理。');
          lines.push('');

          // AC14: Mark as reminded and set post-reminder auto-close timer (15s default).
          for (const item of toRemind) {
            const entry = pendingClosures.get(item.closureId);
            if (entry) {
              entry.reminded = true;
              clearTimeout(entry.timer);
              const autoCloseTimer = setTimeout(() => {
                if (pendingClosures.has(item.closureId)) {
                  appendAuditLog({
                    event: 'closure_detected',
                    closureId: item.closureId,
                    agentId: entry.agentId,
                    label: entry.label,
                    duration: entry.duration,
                    method: 'post_reminder_auto_close',
                    latencyMs: Date.now() - entry.completedAt,
                  });
                  pendingClosures.delete(item.closureId);
                }
              }, autoCloseDelayMs);
              if (autoCloseTimer.unref) autoCloseTimer.unref();
              entry.timer = autoCloseTimer;
            }
          }

          appendAuditLog({
            event: 'reminder_injected',
            sessionKey,
            completionCount: toRemind.length,
            closureIds: toRemind.map(t => t.closureId),
          });

          return { prependContext: lines.join('\n') };
        } catch (e) {
          api.logger?.warn?.(`[aco-closure-guard] before_prompt_build error: ${e.message}`);
          return null;
        }
      },
      { priority: 980 },
    );

    // --- Hook: message_sending ---
    api.on(
      'message_sending',
      (event, ctx) => {
        try {
          if (pendingClosures.size === 0) return null;

          const content = String(event.content || '');
          if (content.length <= 50) return null;

          const sessionKey = String(ctx?.sessionKey || ctx?.sessionId || '');
          if (!sessionKey.includes('feishu')) return null;

          const now = Date.now();
          for (const [closureId, data] of pendingClosures) {
            if (data.completedAt <= now) {
              clearTimeout(data.timer);
              appendAuditLog({
                event: 'closure_detected',
                closureId,
                agentId: data.agentId,
                label: data.label,
                duration: data.duration,
                closedBySessionKey: sessionKey,
                latencyMs: now - data.completedAt,
              });
              pendingClosures.delete(closureId);
            }
          }
        } catch (e) {
          api.logger?.warn?.(`[aco-closure-guard] message_sending error: ${e.message}`);
        }
        return null;
      },
      { priority: 900 },
    );

    api.logger?.info?.(`[aco-closure-guard] plugin registered (v1.0.0 — closure guard)`);
  },
};
