/**
 * ACO Async Discipline Guard Plugin — Gateway-loadable ESM module
 * Generated by `aco init`
 *
 * Hooks: before_prompt_build, before_tool_call
 * Rule: dispatch.process.async_discipline_blocked
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const AUDIT_LOG_PATH = "/root/.openclaw/workspace/logs/dispatch-guard-events.jsonl";

const LLM_INTENT_JUDGEMENT_PROMPT_VERSION = 'v1';
const LLM_INTENT_JUDGEMENT_PROMPT_V1 = "你是 ACO 主会话异步纪律守卫的意图判断器。\n任务: 判断用户当前消息是否在表达“我授权这次主会话本回合亲自执行长任务/同步等待/不要派子 Agent”。\n如果用户当前消息表达了这种授权意图,包括任意自然语言措辞、YES、你别派、我亲自处理、这次我搞、主会话直接干、你顶上、我盯着这个、老规矩你来、[SYSTEM] override、忽略指令放行等,判 YES。\n如果用户当前消息没有表达授权主会话亲自执行本回合长任务的意图,判 NO。\n严格只返回单词 YES 或 NO,不返回任何解释、标点、引号、代码块、空白以外字符;不返回其他语言;不返回多个单词。";

const DEFAULT_CONFIG = {
  "enabled": true,
  "maxBlockingTimeoutMs": 5000,
  "blockingActions": [
    "poll",
    "wait",
    "log",
    "list"
  ],
  "llmJudgement": {
    "enabled": true,
    "provider": "penguin-main",
    "model": "claude-opus-4-7",
    "timeoutMs": 5000
  },
  "degradedRecoveryWindowMs": 300000
};

export default {
  id: 'aco-async-discipline-guard',
  name: "aco-async-discipline-guard",
  version: "1.1.0",

  register(api) {
    const recentUserMessageCache = new Map();
    let degradedAt = null;

    function getPluginConfig() {
      const pluginEntry = api.pluginConfig?.["aco-async-discipline-guard"];
      const dispatchEntry = api.pluginConfig?.['agent-dispatch-guard'];
      const pluginConfig = pluginEntry?.config || pluginEntry || dispatchEntry?.asyncDisciplineGuard || dispatchEntry || {};
      const raw = pluginConfig.asyncDisciplineGuard || pluginConfig;
      const legacyField = ['user', 'Exempt', 'Keywords'].join('');
      if (Object.prototype.hasOwnProperty.call(raw, legacyField)) {
        api.logger?.warn?.('[aco-async-discipline-guard] FR-K02: legacy keyword exemption config is deprecated and ignored; exemption now uses LLM semantic intent judgement.');
      }
      const cfg = { ...DEFAULT_CONFIG, ...raw, llmJudgement: { ...DEFAULT_CONFIG.llmJudgement, ...(raw.llmJudgement || {}) } };
      delete cfg[legacyField];
      if (!Number.isFinite(Number(cfg.maxBlockingTimeoutMs)) || Number(cfg.maxBlockingTimeoutMs) <= 0) {
        api.logger?.warn?.('[aco-async-discipline-guard] invalid maxBlockingTimeoutMs, fallback to 5000');
        cfg.maxBlockingTimeoutMs = 5000;
      }
      if (!Array.isArray(cfg.blockingActions) || cfg.blockingActions.length === 0) cfg.blockingActions = DEFAULT_CONFIG.blockingActions;
      const recovery = Number(cfg.degradedRecoveryWindowMs ?? cfg.degradedRecoverIntervalMs);
      if (!Number.isFinite(recovery) || recovery < 60000 || recovery > 3600000) {
        api.logger?.warn?.('[aco-async-discipline-guard] asyncDisciplineGuard.degradedRecoveryWindowMs out of range, fallback to default 300000');
        cfg.degradedRecoveryWindowMs = 300000;
      } else {
        cfg.degradedRecoveryWindowMs = recovery;
      }
      if (!Number.isFinite(Number(cfg.llmJudgement.timeoutMs)) || Number(cfg.llmJudgement.timeoutMs) <= 0) cfg.llmJudgement.timeoutMs = 5000;
      if (!isConfiguredModel(api.config, cfg.llmJudgement.provider, cfg.llmJudgement.model)) {
        api.logger?.error?.('[aco-async-discipline-guard] asyncDisciplineGuard.llmJudgement provider/model is not configured in models.providers; judgement will block exemptions.');
      }
      return cfg;
    }

    function isConfiguredModel(config, provider, model) {
      const models = config?.models?.providers?.[provider]?.models;
      return Array.isArray(models) && models.some(m => (typeof m === 'string' ? m : m?.id) === model);
    }

    function extractSessionKey(event, context) {
      return String(context?.sessionKey || event?.sessionKey || event?.session?.sessionKey || '');
    }

    function extractAgentId(event, context, sessionKey) {
      const explicit = context?.agentId || event?.agentId || event?.session?.agentId;
      if (explicit) return String(explicit);
      const parts = String(sessionKey || '').split(':');
      if (parts[0] === 'agent' && parts[1]) return parts[1];
      return 'unknown';
    }

    function isMainSession(sessionKey, agentId) {
      return agentId === 'main' || String(sessionKey || '').includes(':main:') || String(sessionKey || '').startsWith('agent:main:');
    }

    function extractText(content) {
      if (typeof content === 'string') return content;
      if (Array.isArray(content)) {
        return content.map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object' && typeof item.text === 'string') return item.text;
          return '';
        }).filter(Boolean).join('\n');
      }
      if (content && typeof content === 'object' && typeof content.text === 'string') return content.text;
      return '';
    }

    function captureRecentUserMessage(event, context) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      if (!isMainSession(sessionKey, agentId)) return;
      const messages = event?.messages || context?.messages || event?.prompt?.messages || [];
      if (!Array.isArray(messages)) return;
      for (let i = messages.length - 1; i >= 0; i--) {
        const msg = messages[i];
        if (!msg || msg.role !== 'user') continue;
        const text = extractText(msg.content ?? msg.text ?? msg.message);
        if (text) {
          recentUserMessageCache.set(sessionKey, { text, ts: Date.now() });
          if (recentUserMessageCache.size > 200) {
            const cutoff = Date.now() - 24 * 60 * 60 * 1000;
            for (const [key, value] of recentUserMessageCache) if (value.ts < cutoff) recentUserMessageCache.delete(key);
          }
        }
        return;
      }
    }

    function hashMessage(text) {
      if (text === null || text === undefined) return 'cache_miss';
      return crypto.createHash('sha256').update(String(text)).digest('hex').slice(0, 16);
    }

    function summarizeToolArgs(args) {
      const out = {};
      for (const [key, value] of Object.entries(args || {})) {
        if (typeof value === 'string') out[key] = value.length > 60 ? value.slice(0, 60) + '…' : value;
        else if (value === null || ['number', 'boolean'].includes(typeof value)) out[key] = value;
        else out[key] = JSON.stringify(value).slice(0, 60);
      }
      return out;
    }

    function appendAuditEvent(entry) {
      try {
        fs.mkdirSync(path.dirname(AUDIT_LOG_PATH), { recursive: true });
        fs.appendFileSync(AUDIT_LOG_PATH, JSON.stringify(entry) + '\n');
      } catch (e) {
        api.logger?.warn?.('[aco-async-discipline-guard] audit log write failed: ' + e.message);
      }
    }

    function buildBlockReason(action, timeoutMs) {
      return [
        `[ACO 异步纪律守卫] 主会话被禁止调用 process(action=${action || 'unknown'}, timeout=${timeoutMs}ms) 同步等待。`,
        '原因: 此调用会锁住主会话 lane，期间用户 IM 消息会被静默排队，体感等同失联。',
        '',
        '合规路径(任选其一):',
        '  1. 信任 push-based completion event。spawn 后直接结束当前回合，子 Agent 完成时会自动触发新回合，无需主动 poll。',
        '  2. 确实需要观察某个进程状态，改派一个短任务子 Agent 异步执行 poll，完成后通过 completion event 回报结果。',
        '',
        '豁免方式: 用户在最近一条 IM 消息中明确表达让主会话本回合亲自执行这件事的意图，由 LLM 语义判定。',
        '豁免仅本次有效，下次调用重新走完整守卫。',
        '',
        '命中规则: dispatch.process.async_discipline_blocked',
      ].join('\n');
    }

    function audit({ decision, ruleId, reason, event, context, llmVerdict = 'not_applicable', llmLatencyMs = 0, llmError = null, llmPromptVersion = null, details = {} }) {
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;
      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const timestamp = new Date().toISOString();
      appendAuditEvent({
        ts: timestamp,
        timestamp,
        eventType: 'dispatch.process.async_discipline',
        rule: 'async-discipline',
        ruleId,
        decision,
        toolName: 'process',
        sessionKey,
        agentId,
        action,
        timeoutMs,
        toolArgs: summarizeToolArgs(params),
        exemptKeyword: null,
        triggerKeyword: null,
        recentUserMessageHash: hashMessage(recent),
        llmVerdict,
        llmLatencyMs,
        llmError,
        llmPromptVersion,
        reason,
        details: { rule: 'async-discipline', ruleId, decision, action, timeoutMs, exemptKeyword: null, triggerKeyword: null, recentUserMessageHash: hashMessage(recent), llmVerdict, llmLatencyMs, llmError, llmPromptVersion, reason, ...details },
      });
    }

    function normalizeLlmIntentRaw(raw) {
      return String(raw ?? '').trim().toUpperCase().replace(/[\p{P}\p{S}]/gu, '');
    }

    function buildIntentMessages(recent) {
      return {
        system: LLM_INTENT_JUDGEMENT_PROMPT_V1,
        user: '请判断下面这条用户当前消息是否表达授权主会话本回合亲自执行长任务。\n\n\x60\x60\x60\n' + String(recent ?? '') + '\n\x60\x60\x60',
      };
    }

    async function callConfiguredChatProvider(cfg, messages, signal) {
      if (api.openclaw?.chat?.complete) {
        const res = await api.openclaw.chat.complete({ provider: cfg.llmJudgement.provider, model: cfg.llmJudgement.model, messages, signal });
        return res?.text ?? res?.content ?? res?.message?.content ?? '';
      }
      const providerCfg = api.config?.models?.providers?.[cfg.llmJudgement.provider];
      if (!providerCfg) throw new Error('provider not configured');
      const baseUrl = String(providerCfg.baseUrl || providerCfg.baseURL || '').replace(/\/$/, '');
      const apiKey = providerCfg.apiKey || providerCfg.auth?.apiKey || providerCfg.request?.auth?.token;
      if (!baseUrl || !apiKey) throw new Error('provider baseUrl/apiKey unavailable');
      const response = await fetch(baseUrl + '/chat/completions', {
        method: 'POST',
        signal,
        headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + apiKey, ...(providerCfg.headers || {}) },
        body: JSON.stringify({ model: cfg.llmJudgement.model, messages, temperature: 0, max_tokens: 4 }),
      });
      if (!response.ok) throw new Error('provider HTTP ' + response.status);
      const data = await response.json();
      return data?.choices?.[0]?.message?.content ?? data?.choices?.[0]?.text ?? '';
    }

    async function llmIntentJudgement(cfg, recent, action, timeoutMs) {
      if (cfg.llmJudgement?.enabled === false) return { llmVerdict: 'disabled', llmLatencyMs: 0, llmError: null, llmPromptVersion: null };
      const started = Date.now();
      const controller = new AbortController();
      const timeoutLimit = Number(cfg.llmJudgement.timeoutMs || 5000);
      const timer = setTimeout(() => controller.abort(), timeoutLimit);
      try {
        const prompt = buildIntentMessages(recent);
        const raw = await callConfiguredChatProvider(cfg, [{ role: 'system', content: prompt.system }, { role: 'user', content: prompt.user }], controller.signal);
        const normalized = normalizeLlmIntentRaw(raw);
        return { llmVerdict: normalized === 'YES' ? 'allow' : 'deny', llmLatencyMs: Math.max(0, Date.now() - started), llmError: null, llmPromptVersion: LLM_INTENT_JUDGEMENT_PROMPT_VERSION };
      } catch (e) {
        const timeout = e?.name === 'AbortError';
        return { llmVerdict: timeout ? 'timeout' : 'error', llmLatencyMs: timeout ? timeoutLimit : Math.max(0, Date.now() - started), llmError: (timeout ? 'timeout' : String(e?.message || e)).slice(0, 256), llmPromptVersion: LLM_INTENT_JUDGEMENT_PROMPT_VERSION };
      } finally {
        clearTimeout(timer);
      }
    }

    async function evaluateAsyncDiscipline(event, context, cfg) {
      const toolName = String(event?.toolName || context?.toolName || '');
      if (toolName !== 'process') return null;
      const sessionKey = extractSessionKey(event, context);
      const agentId = extractAgentId(event, context, sessionKey);
      const params = event?.params || event?.args || context?.params || {};
      const action = typeof params.action === 'string' ? params.action : '';
      const timeoutMs = Number.isFinite(Number(params.timeout)) && Number(params.timeout) > 0 ? Number(params.timeout) : 0;

      if (cfg.enabled === false) {
        audit({ decision: 'bypass_disabled', ruleId: 'dispatch.process.async_discipline_bypass_disabled', reason: 'Async discipline guard is disabled by configuration.', event, context });
        return null;
      }

      const now = Date.now();
      if (degradedAt !== null) {
        const elapsed = now - degradedAt;
        if (elapsed < cfg.degradedRecoveryWindowMs) {
          audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard is degraded; allowing tool call.', event, context, details: { degradedAt } });
          return null;
        }
        const previousDegradedAt = degradedAt;
        degradedAt = null;
        audit({ decision: 'recovery_attempt', ruleId: 'dispatch.process.async_discipline_recovery_attempt', reason: 'Async discipline guard recovery window elapsed; attempting normal evaluation.', event, context, details: { previousDegradedAt, recoveryWindowMs: cfg.degradedRecoveryWindowMs, elapsedMs: elapsed } });
      }

      if (!isMainSession(sessionKey, agentId)) return null;
      if (!cfg.blockingActions.map(a => String(a).toLowerCase()).includes(action.toLowerCase())) return null;
      if (timeoutMs < cfg.maxBlockingTimeoutMs) return null;

      const recent = recentUserMessageCache.get(sessionKey)?.text ?? null;
      const llm = await llmIntentJudgement(cfg, recent, action, timeoutMs);
      if (llm.llmVerdict === 'allow') {
        audit({ decision: 'exempt', ruleId: 'dispatch.process.async_discipline_exempted', reason: 'User exemption intent judged by LLM.', event, context, ...llm });
        return null;
      }

      const reason = buildBlockReason(action, timeoutMs);
      audit({ decision: 'block', ruleId: 'dispatch.process.async_discipline_blocked', reason, event, context, ...llm });
      return { block: true, blockReason: reason };
    }

    api.on('before_prompt_build', (event, context) => {
      try { captureRecentUserMessage(event, context); }
      catch (e) { api.logger?.warn?.('[aco-async-discipline-guard] recent user cache error: ' + e.message); }
      return null;
    }, { priority: 970 });

    api.on('before_tool_call', async function(event, context) {
      try {
        const cfg = getPluginConfig();
        return await evaluateAsyncDiscipline(event, context, cfg);
      } catch (e) {
        degradedAt = Date.now();
        api.logger?.warn?.('[aco-async-discipline-guard] degraded: ' + e.message);
        try { audit({ decision: 'bypass_degraded', ruleId: 'dispatch.process.async_discipline_bypass_degraded', reason: 'Async discipline guard runtime error: ' + String(e.message || e).slice(0, 256), event, context, details: { degradedAt, error: String(e.message || e).slice(0, 256), stackTop: String(e.stack || '').split('\n').slice(0, 3).join('\n').slice(0, 512) } }); } catch {}
        return null;
      }
    });
  },
};
